### ISSUE TITLE
YoutubeDataApi().fetchVideoData(widget.videoId) & YoutubeDataApi().fetchPlayListVideos(widget.videoId)

### ISSUE THREAD

**Issue by abhihasabe** [modwedar/YoutubeDataApi#8]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 5273): Receiver: null
E/flutter ( 5273): Tried calling: []("defaultText")
E/flutter ( 5273): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter ( 5273): #1      new VideoPage.fromMap (package:youtube_data_api/models/video_page.dart:47:167)
E/flutter ( 5273): #2      YoutubeDataApi.fetchVideoData (package:youtube_data_api/youtube_data_api.dart:435:28)
E/flutter ( 5273): <asynchronous suspension>
E/flutter ( 5273): #3      _VideoDetailPageState.showData (package:entertenment_hub/video_detail_page.dart:630:9)
E/flutter ( 5273): <asynchronous suspension>

**Comment by Muhammad-Ullah** [comment]
Did you find a solution of this?

**Comment by ebel-frank** [comment]
Yes, I created a PR. 

Now I am working on a new project and I wonder why the PR hasn't been merged

**Comment by SagarKoliRetire100** [comment]
I am facing this issue. Can someone please help me resolving it.

**Comment by AsadDev40** [comment]
i got the issue when i gave video ids to this method but it did not get these videos by ids instead of this it gets related videos not the actual videos which ids i gave to this method.Any one help me to solve this
